apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-01-28T11:20:30Z"
  generation: 1
  labels:
    k8s-app: chris-nginx-2
  name: chris-nginx-2
  namespace: chris-namespace
  resourceVersion: "109139"
  uid: a566427a-6e96-4e72-9e21-6c990a423d31
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: chris-nginx-2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: chris-nginx-2
      name: chris-nginx-2
    spec:
      containers:
      - image: registry.nutanix.com:5000/chris-nginx-2:1.0
        imagePullPolicy: IfNotPresent
        name: chris-nginx-2
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2022-01-28T11:20:31Z"
    lastUpdateTime: "2022-01-28T11:20:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-28T11:20:30Z"
    lastUpdateTime: "2022-01-28T11:20:31Z"
    message: ReplicaSet "chris-nginx-2-6c5867d78f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
