apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: chris-nginx-2
  name: chris-nginx-2
  namespace: cd-chris-nginx
spec:
  ports:
  - name: tcp-8123-80-z69vc
    nodePort: 34321
    port: 8123
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: chris-nginx-2
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
