apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5udXRhbml4LmNvbTo1MDAwIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NmJuVjBZVzVwZUM4MGRRPT0iCgkJfQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE4LjA5LjggKGxpbnV4KSIKCX0KfQ==
kind: Secret
metadata:
  name: regcred
  namespace: cd-chris-nginx
type: kubernetes.io/dockerconfigjson
